# Generated by Django 4.0.5 on 2022-07-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iride_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Age',
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='Weight',
            field=models.TextField(max_length=5),
        ),
    ]
