# Generated by Django 4.0.5 on 2022-07-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iride_app', '0002_alter_users_age_alter_users_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Rider',
        ),
    ]
