# Generated by Django 4.0.5 on 2022-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iride_app', '0003_rename_users_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rider',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rider',
            name='Weight',
            field=models.IntegerField(),
        ),
    ]
